import Foundation

struct VenueWalkTimes {
    private static let stageToCluster: [String: String] = [
        "Amare \u{2013} Concertzaal": "amare",
        "Amare \u{2013} Danstheater": "amare",
        "Amare \u{2013} Studio": "amare",
        "Amare \u{2013} Swing": "amare",
        "Nieuwe Kerk": "nieuweKerk",
        "Theater aan het Spui \u{2013} Zaal 1": "taspui",
        "Theater aan het Spui \u{2013} Zaal 2": "taspui",
        "Korzo \u{2013} Zaal": "korzo",
        "Korzo \u{2013} Studio": "korzo",
        "Koninklijke Schouwburg": "schouwburg",
        "Pulchri Studio": "pulchri",
        "Duitse Kerk": "duitseKerk",
        "Lutherse Kerk": "lutherseKerk",
        "Paleiskerk": "paleiskerk",
        "Grote Kerk": "groteKerk",
        "PAARD I": "paard",
        "PAARD II": "paard",
        "Koorenhuis": "koorenhuis",
        "Concordia": "concordia",
        "The Grey Space \u{2013} Basement": "greySpace",
        "Das Leben am Haverkamp": "dasLeben",
        "Quartair": "quartair",
        "West Den Haag \u{2013} Auditorium": "westDenHaag",
        "Laak": "laak",
    ]

    private static let times: [String: Int] = [
        "amare-nieuweKerk": 1,
        "amare-taspui": 2,
        "amare-korzo": 3,
        "amare-greySpace": 5,
        "amare-duitseKerk": 5,
        "amare-lutherseKerk": 5,
        "amare-schouwburg": 6,
        "amare-pulchri": 7,
        "amare-dasLeben": 7,
        "amare-paleiskerk": 7,
        "amare-paard": 8,
        "amare-koorenhuis": 8,
        "amare-concordia": 9,
        "amare-groteKerk": 10,
        "amare-quartair": 12,
        "amare-westDenHaag": 15,
        "amare-laak": 25,
        "korzo-schouwburg": 4,
        "korzo-pulchri": 5,
        "korzo-paleiskerk": 5,
        "korzo-duitseKerk": 5,
        "korzo-groteKerk": 8,
        "korzo-nieuweKerk": 3,
        "korzo-taspui": 3,
        "koorenhuis-paard": 2,
        "concordia-paard": 2,
        "groteKerk-paard": 3,
        "lutherseKerk-paard": 5,
        "greySpace-paard": 6,
        "pulchri-schouwburg": 2,
        "duitseKerk-schouwburg": 3,
        "concordia-groteKerk": 2,
        "groteKerk-koorenhuis": 2,
        "nieuweKerk-taspui": 1,
        "concordia-koorenhuis": 2,
        "duitseKerk-pulchri": 3,
        "dasLeben-greySpace": 3,
        "laak-westDenHaag": 15,
        "laak-quartair": 20,
        "laak-paard": 22,
        "laak-groteKerk": 23,
        "laak-concordia": 23,
        "laak-koorenhuis": 22,
        "laak-greySpace": 20,
        "laak-dasLeben": 20,
        "laak-lutherseKerk": 25,
        "laak-paleiskerk": 25,
        "laak-duitseKerk": 27,
        "laak-schouwburg": 28,
        "laak-pulchri": 28,
        "laak-korzo": 27,
        "laak-nieuweKerk": 25,
        "laak-taspui": 25,
        "quartair-westDenHaag": 8,
    ]

    static func walkingMinutes(fromStage a: String, toStage b: String) -> Int? {
        guard let ca = stageToCluster[a], let cb = stageToCluster[b] else { return nil }
        if ca == cb { return 0 }
        let key = [ca, cb].sorted().joined(separator: "-")
        return times[key] ?? 10
    }
}
